# Generated by Django 5.1.4 on 2024-12-14 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('250287e7-9f16-4618-bf25-b3154d497fd4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
